### ISSUE TITLE
zone.php draw zone in fr_FR not possible

### ISSUE THREAD

**Issue by alex001x** [opendcim/openDCIM#1564] opened 2024-10-02 13:27 UTC
Hello,

when I choose the language FR, impossible to draw the frame of the zone
maybe problem comes from the spelling "Data Center" poeditor in French "Salle (Data Center)" conflict interpretation php "()"

**Comment by alex001x** [comment] 2024-10-02 14:06
zone.php page but you have to load a data center map image to define a zone, in opendcim.org image loading is not possible (writing rights prohibited on the folder) 
when the language is French fr_FR, it is impossible to draw the area

**Comment by wilpig** [comment] 2024-10-02 14:09
https://dev.opendcim.org/zone_stats.php?zone=2

Someone had changed the image path.  I've corrected them.

**Comment by alex001x** [comment] 2024-10-02 14:11
print screen
![image](https://github.com/user-attachments/assets/a84b8a66-eb17-476f-af53-d40a8d2fca92)

**Comment by wilpig** [comment] 2024-10-02 14:16
I see the problem in the debugger.  I'll try to get a fix this afternoon.   It's a javascript error caused by the data injection.

https://github.com/opendcim/openDCIM/blob/master/zone.php#L237

**Comment by wilpig** [comment] 2024-10-03 22:34
fixed in 544b34d9ea71a659f9ad171034e13becb90b5db9

**Closed by wilpig** 2024-10-03 22:34 UTC
Labels: bug
